var config = {
    content: ["./index.html", "./src/**/*.{ts,tsx}"],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "carbon-blue-10": "#d0e2ff",
                "carbon-blue-20": "#a6c8ff",
                "carbon-blue-30": "#78a9ff",
                "carbon-blue-40": "#4589ff",
                "carbon-blue-50": "#0f62fe",
                "carbon-blue-60": "#0043ce",
                "carbon-blue-70": "#002d9c",
                "carbon-blue-80": "#001d6c",
                "carbon-blue-90": "#001141",
                "carbon-blue-100": "#00071f",
                "carbon-gray-10": "#f4f4f4",
                "carbon-gray-20": "#e0e0e0",
                "carbon-gray-30": "#c6c6c6",
                "carbon-gray-40": "#a8a8a8",
                "carbon-gray-50": "#8d8d8d",
                "carbon-gray-60": "#6f6f6f",
                "carbon-gray-70": "#525252",
                "carbon-gray-80": "#393939",
                "carbon-gray-90": "#262626",
                "carbon-gray-100": "#161616",
                "carbon-red-10": "#fff1f1",
                "carbon-red-20": "#ffd7d9",
                "carbon-red-30": "#ffb3b8",
                "carbon-red-40": "#ff8389",
                "carbon-red-50": "#fa4d56",
                "carbon-red-60": "#da1e28",
                "carbon-red-70": "#a2191f",
                "carbon-red-80": "#750e13",
                "carbon-green-10": "#defbe6",
                "carbon-green-20": "#a7f0ba",
                "carbon-green-30": "#6fdc8c",
                "carbon-green-40": "#42be65",
                "carbon-green-50": "#24a148",
                "carbon-green-60": "#198038",
                "carbon-green-70": "#0e6027",
                "carbon-yellow-10": "#fcf4d6",
                "carbon-yellow-20": "#fddc69",
                "carbon-yellow-30": "#f1c21b",
                "carbon-yellow-40": "#d2a106",
                "carbon-yellow-50": "#b28600",
                "carbon-teal-10": "#d9fbfb",
                "carbon-teal-20": "#9ef0f0",
                "carbon-teal-30": "#3ddbd9",
                "carbon-teal-40": "#08bdba",
                "carbon-teal-50": "#009d9a",
                "carbon-teal-60": "#007d79",
                "carbon-teal-70": "#005d5d",
                "carbon-white": "#ffffff",
                "carbon-black": "#000000",
                primary: {
                    DEFAULT: "var(--cds-border-interactive)",
                    hover: "var(--cds-link-primary-hover)",
                },
                background: "var(--cds-background)",
                surface: {
                    DEFAULT: "var(--cds-layer)",
                    hover: "var(--cds-layer-hover)",
                    active: "var(--cds-layer-active)",
                    selected: "var(--cds-layer-selected)",
                },
                "text-primary": "var(--cds-text-primary)",
                "text-secondary": "var(--cds-text-secondary)",
                "text-placeholder": "var(--cds-text-placeholder)",
                "text-helper": "var(--cds-text-helper)",
                "border-subtle": "var(--cds-border-subtle)",
                "border-strong": "var(--cds-border-strong)",
                "border-interactive": "var(--cds-border-interactive)",
                danger: "var(--cds-support-error)",
                success: "var(--cds-support-success)",
                warning: "var(--cds-support-warning)",
                info: "var(--cds-support-info)",
            },
            spacing: {
                1: "0.25rem",
                2: "0.5rem",
                3: "0.75rem",
                4: "1rem",
                5: "1.25rem",
                6: "1.5rem",
                7: "1.75rem",
                8: "2rem",
                9: "2.25rem",
                10: "2.5rem",
                12: "3rem",
                13: "3.25rem",
                14: "3.5rem",
                16: "4rem",
                20: "5rem",
                24: "6rem",
                28: "7rem",
                32: "8rem",
                36: "9rem",
                40: "10rem",
                44: "11rem",
                48: "12rem",
                56: "14rem",
                64: "16rem",
                72: "18rem",
                80: "20rem",
                96: "24rem",
            },
            borderRadius: {
                DEFAULT: "0",
                sm: "0.25rem",
                md: "0",
            },
            fontFamily: {
                sans: ['"IBM Plex Sans"', "system-ui", "-apple-system", "sans-serif"],
                condensed: [
                    '"IBM Plex Sans Condensed"',
                    '"IBM Plex Sans"',
                    "system-ui",
                    "sans-serif",
                ],
            },
            fontSize: {
                "productive-01": ["0.75rem", { lineHeight: "1rem", fontWeight: "400" }],
                "productive-02": [
                    "0.875rem",
                    { lineHeight: "1.125rem", fontWeight: "400" },
                ],
                "productive-03": ["1rem", { lineHeight: "1.375rem", fontWeight: "400" }],
                "productive-04": [
                    "1.125rem",
                    { lineHeight: "1.5rem", fontWeight: "600" },
                ],
                "productive-05": [
                    "1.25rem",
                    { lineHeight: "1.625rem", fontWeight: "600" },
                ],
                "expressive-01": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
                "expressive-02": ["1.25rem", { lineHeight: "1.75rem", fontWeight: "400" }],
                "expressive-03": [
                    "1.5rem",
                    { lineHeight: "2rem", fontWeight: "400" },
                ],
                "expressive-04": [
                    "2rem",
                    { lineHeight: "2.5rem", fontWeight: "600" },
                ],
                "expressive-05": [
                    "2.5rem",
                    { lineHeight: "3rem", fontWeight: "600" },
                ],
                "expressive-06": [
                    "3rem",
                    { lineHeight: "3.5rem", fontWeight: "300" },
                ],
            },
            boxShadow: {
                sm: "0 1px 3px rgba(0, 0, 0, 0.04)",
                DEFAULT: "0 2px 6px rgba(0, 0, 0, 0.06)",
                lg: "0 4px 12px rgba(0, 0, 0, 0.08)",
            },
            keyframes: {
                "skeleton-pulse": {
                    "0%, 100%": { opacity: "1" },
                    "50%": { opacity: "0.4" },
                },
            },
            animation: {
                "skeleton-pulse": "skeleton-pulse 1.5s ease-in-out infinite",
            },
        },
    },
    plugins: [],
};
export default config;
